### ISSUE TITLE
Memory leaked after tinyobj_parse_obj do file_reader

### ISSUE THREAD

**Issue by refactor** [syoyo/tinyobjloader-c#45] opened 2020-12-31 09:18 UTC
buf hold the readed file content, but no place to free it.

**Comment by syoyo** [comment] 2020-12-31 09:20
You need to show the line

**Comment by nashidau** [comment] 2021-03-06 04:50
There is no line for the leak.  The problem is in the file reader buf is allocated and passed back in.  But it isn't freed.
I think a better fix is to add a context pointer to the file reader.  Then caller can clean up after.

**Comment by syoyo** [comment] 2021-03-06 05:11
@nashidau Thanks for the detailed information. App user need to explicitly manage the pointer to `buf`(since there is no `free` when the memory is allocated with mmap). 

At least I need to add freeing pointer code in `example/viewer` example and describe how to manage memory in README.

> I think a better fix is to add a context pointer to the file reader

Yes, this is the best way to fix. I'll do that.

**Comment by nashidau** [comment] 2021-03-06 05:12
I jus tmade a pull request that adds it.

**Comment by syoyo** [comment] 2021-03-06 08:48
@nashidau :+1:  

PR https://github.com/syoyo/tinyobjloader-c/pull/46 has been merged so close the issue.

**Closed by syoyo** 2021-03-06 08:48 UTC
Labels: enhancement
